# https://git.drupalcode.org/project/gitlab_templates/
variables:
  SKIP_CSPELL: 1
  SKIP_ESLINT: 1
  SKIP_PHPMD: 1
  SKIP_STYLELINT: 1
include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - "/includes/include.drupalci.main.yml"
      - "/includes/include.drupalci.variables.yml"
      - "/includes/include.drupalci.workflows.yml"

